<?php

/**
 * @file
 * Provides an author management entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function author_management_theme() {
  return [
    'author_management' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for author management templates.
 *
 * Default template: author-management.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the author management information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_author_management(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
