<?php

/**
 * @file
 * Provides a question survey entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function question_survey_theme() {
  return [
    'question_survey' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for question survey templates.
 *
 * Default template: question-survey.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the question survey information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_question_survey(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
